<a href="https://colab.research.google.com/github/MehrabHussain47/Problem-Solving/blob/master/_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [ ]:
# To avoid overwriting the output, please code here
import numpy as np
# Vector is a 1d array.
v = np.array([1,2,3])
print(v)  # Print this vector.
print(v.shape)  # It is a 1 row x 3 column matrix (1d array).
# Matrix is a 2d array.
m = np.array([[1,2,3],[4,5,6]])
print(m)  # Print this matrix
print(m.shape)  # It is a 2 row x 3 column matrix (2d array).
# Basic difference of vector and matrix is: vector is a 1d array, matrix is a 2d array.

[1 2 3]
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)


**2. How to import `NumPy` library?**

In [ ]:
# To avoid overwriting the output, please code here

In [75]:
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [ ]:
# To avoid overwriting the output, please code here

In [ ]:
my_list = [1,2,3,4,5]
print(my_list)
list_to_array = np.array(my_list)
print(list_to_array)
print(list_to_array.dtype)  # To know the type of numbers
print(type(list_to_array))  # To know the array class

[1, 2, 3, 4, 5]
[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

array([0, 1, 2, 3, 4, 5])

In [ ]:
# To avoid overwriting the output, please code here

In [ ]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros`**

array([ 0.,  0.,  0.,  0.,  0.])

In [ ]:
# To avoid overwriting the output, please code here

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

**6. Generate the following `matrix`.**

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [ ]:
# To avoid overwriting the output, please code here

In [ ]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

[ 1.  1.  1.  1.  1.]

In [ ]:
# To avoid overwriting the output, please code here

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

**8. Generate an array of "5" tens.**

array([10., 10., 10., 10., 10.])

In [ ]:
# To avoid overwriting the output, please code here

In [ ]:
np.full(5, 10, dtype=float)

array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

In [ ]:
# To avoid overwriting the output, please code here

In [ ]:
np.arange(52,100,2)

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

In [ ]:
np.linspace(0,1,10, retstep=1)

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 np.float64(0.1111111111111111))

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [ ]:
# To avoid overwriting the output, please code here

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
# Generating vector array

In [ ]:
v = np.arange(25)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# reshape to convert into 2-d

In [ ]:
m = v.reshape(5,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# Using shape

In [ ]:
v2 = np.arange(25)
v2.shape = (5,5)
v2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

In [ ]:
# To avoid overwriting the output, please code here

In [ ]:
m2 = np.arange(0.1,2.6,0.1)
m2.shape = (5,5)
m2

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# To avoid overwriting the output, please code here

In [ ]:
m3 = np.linspace(0,24,25, dtype=int)
m3.shape = (5,5)
m3
print(f"array({m})")

array([[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]])


**14. What is the main difference between `linspace()` and `arange()`?**

linspace(start, stop, num): Generates num equally spaced values between start and stop (inclusive of start).<br>
arange(start, stop, step): Generates values from start to stop with a specified step size, but the stop value is not included.<br>
arange() takes a step size as the third argument, while linspace() takes the number of points.<br>
In summary, linspace() focuses on the number of elements, while arange() focuses on the step size between elements.

**15. How to generate a single random integer number using NumPy built-in function?**

211

In [76]:
# To avoid overwriting the output, please code here

rand_num2 = np.random.choice([211]) # doesn't support randint because it will gneerate in between 0 to 211
# must have to [] outside the number otherwise it will generate random
print(rand_num2)

211


**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
, [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
, [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
, [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
, [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
, [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
, [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]

In [77]:
# To avoid overwriting the output, please code here

In [84]:
matrix = np.random.rand(7,5)
print(matrix)

[[0.19434222 0.77332601 0.97425866 0.86230978 0.78042665]
 [0.98503228 0.75356961 0.00404811 0.26947943 0.41049214]
 [0.42822383 0.29784182 0.40113234 0.12065699 0.98069967]
 [0.40612049 0.56921076 0.3436055  0.78887278 0.41137241]
 [0.35927142 0.39949891 0.30183088 0.77521978 0.92621293]
 [0.32531031 0.95287067 0.0139484  0.53346568 0.30458203]
 [0.88286    0.25062272 0.67741183 0.81042409 0.43214805]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [ ]:
# To avoid overwriting the output, please code here

In [89]:
matrix = 5 * np.eye(5)
matrix

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])