<a href="https://colab.research.google.com/github/MehrabHussain47/Problem-Solving/blob/master/_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [12]:
# To avoid overwriting the output, please code here
import numpy as np
# Vector is a 1d array.
v = np.array([1,2,3])
print(v)  # Print this vector.
print(v.shape)  # It is a 1 row x 3 column matrix (1d array).
# Matrix is a 2d array.
m = np.array([[1,2,3],[4,5,6]])
print(m)  # Print this matrix
print(m.shape)  # It is a 2 row x 3 column matrix (2d array).
# Basic difference of vector and matrix is: vector is a 1d array, matrix is a 2d array.

[1 2 3]
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)


**2. How to import `NumPy` library?**

In [ ]:
# To avoid overwriting the output, please code here

In [1]:
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [ ]:
# To avoid overwriting the output, please code here

In [3]:
my_list = [1,2,3,4,5]
print(my_list)
list_to_array = np.array(my_list)
print(list_to_array)
print(list_to_array.dtype)  # To know the type of numbers
print(type(list_to_array))  # To know the array class

[1, 2, 3, 4, 5]
[1 2 3 4 5]
int64
<class 'numpy.ndarray'>
